spring:
  profiles:
    active: dev #激活开发环境配置

---

server:
  port: 8001


mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml
  type-aliases-package: com.myweb.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  profiles: dev #开发环境
  application:
    name: microservice-product-config_bus # 服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #	 url: jdbc:mysql//127.0.0.1:3306/springcloud_db01?serverTimeZone=GMT%2B8
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db01
    username: root
    password: Zwm1986!
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150


eureka:
  client:
    register-with-eureka: true #服务注册开关
    fetch-registry: true # 服务发现开关
    service-url: #注册到服务端eurekaServer，多个client用逗号分隔
    #		 defaultZone: http://localhost:6001/eureka
      defaultZone: http://eureka6001.com:6001/eureka


  instance:
    instance-id: ${spring.application.name}:${server.port} #指定实例ID
    prefer-ip-address: true #显示ip地址

---

server:
  port: 8001


mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml
  type-aliases-package: com.myweb.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  profiles: prod #开发环境
  application:
  name: microservice-product-config #重要配置，以后服务与服务之间的调用一般都是根据这个name

  datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.cj.jdbc.Driver
  #	 url: jdbc:mysql//127.0.0.1:3306/springcloud_db01?serverTimeZone=GMT%2B8
  url: jdbc:mysql://127.0.0.1:3306/springcloud_db01
  username: root
  password: Zwm1986!
  dbcp2:
    min-idle: 5
    initial-size: 5
    max-total: 5
    max-wait-millis: 150


eureka:
  client:
    register-with-eureka: true #服务注册开关
    fetch-registry: true # 服务发现开关
    service-url: #注册到服务端eurekaServer，多个client用逗号分隔
    #		 defaultZone: http://localhost:6001/eureka
      defaultZone: http://eureka6001.com:6001/eureka

  instance:
    instance-id: ${spring.application.name}:${server.port} #指定实例ID
    prefer-ip-address: true #显示ip地址
